const IDIOMS = [
  {
    "english": "へそを曲げる",
    "japanese": "機嫌をそこねて意固地になる。",
    "yomi": "",
    "category": "へそ",
    "superCategory": "からだに関する慣用句",
    "example": "弟はささいなことでへそを曲げて、口をきかなくなった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "へそで茶をわかす",
    "japanese": "おかしくてたまらない。",
    "yomi": "",
    "category": "へそ",
    "superCategory": "からだに関する慣用句",
    "example": "あの下手な役者が主役だなんて、へそで茶をわかす話だ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "口が重い",
    "japanese": "あまりしゃべらない。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "彼は口が重く、自分のことをめったに話さない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "口がかたい",
    "japanese": "秘密を守り、しゃべらない。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "彼女は口がかたいので、秘密を打ち明けても安心だ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "口が軽い",
    "japanese": "秘密を人に話す。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "口が軽い人には、大事な話をしないほうがよい。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "口車に乗る",
    "japanese": "相手の巧みな話にだまされる。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "うまい話に口車に乗って、損をしてしまった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "口に合う",
    "japanese": "ある食べ物がその人の好みに合う。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "この土地の料理は、私の口によく合う。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "大口をたたく",
    "japanese": "偉そうなことを言う。ほらを吹く。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "練習もせずに優勝すると大口をたたく。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "開いた口がふさがらない",
    "japanese": "あきれてものも言えない。",
    "yomi": "",
    "category": "口",
    "superCategory": "からだに関する慣用句",
    "example": "あまりの言い訳に、開いた口がふさがらなかった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "尻が重い",
    "japanese": "なかなか動こうとしない。",
    "yomi": "",
    "category": "尻",
    "superCategory": "からだに関する慣用句",
    "example": "兄は尻が重く、なかなか手伝いに来ない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "尻に火がつく",
    "japanese": "事態がさしせまり、余裕がなくなる。",
    "yomi": "",
    "category": "尻",
    "superCategory": "からだに関する慣用句",
    "example": "提出日が近づき、ようやく尻に火がついた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "尻をぬぐう",
    "japanese": "人の失敗の後始末をする。",
    "yomi": "",
    "category": "尻",
    "superCategory": "からだに関する慣用句",
    "example": "弟の失敗の尻をぬぐうのは、いつも私だ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手がつけられない",
    "japanese": "とるべき方法や対策がない。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "火の勢いが強く、もう手がつけられない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手ぐすねを引く",
    "japanese": "十分に用意して機会を待つ。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "相手チームは手ぐすねを引いて待ち構えていた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手に汗握る",
    "japanese": "緊迫した状況にはらはらする。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "手に汗握る接戦に、観客はわきあがった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手のひらを返す",
    "japanese": "それまでと態度を大きく変える。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "手のひらを返すように対応がよくなった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "手を打つ",
    "japanese": "必要な対策をとる。話し合いをまとめる。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "問題が大きくなる前に手を打つべきだ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手を貸す",
    "japanese": "手伝う。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "忙しい母に手を貸す。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "手をこまぬく",
    "japanese": "何もしないで人のするままにしておく。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "手をこまぬいて人のするままにしていてはいけない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "手を抜く",
    "japanese": "なすべきことを十分にしない。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "どんな仕事でも手を抜いてはいけない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手を引く",
    "japanese": "関係を断つ。それまでの仕事をやめる。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "彼はその計画から早々に手を引いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手を広げる",
    "japanese": "関係する範囲を広くする。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "事業の手を広げすぎて、失敗した。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "手を焼く",
    "japanese": "処理に困ってもてあます。手こずる。",
    "yomi": "",
    "category": "手",
    "superCategory": "からだに関する慣用句",
    "example": "いたずらばかりする弟に手を焼いている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "爪をとぐ",
    "japanese": "野心を実現するための準備をする。",
    "yomi": "",
    "category": "爪",
    "superCategory": "からだに関する慣用句",
    "example": "次の試合に向けて、ひそかに爪をといでいる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目の当たり",
    "japanese": "自分のすぐ目の前で見ること。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "事故の瞬間を目の当たりにして、言葉を失った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目がくらむ",
    "japanese": "魅力あるものにまどわされる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "付録に目がくらんで、雑誌を買った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "目が高い（=目が利く）",
    "japanese": "よいものを見分けられる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "この作品を選ぶなんて、お目が高い。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "目が飛び出る",
    "japanese": "値段が高くてびっくりする。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "値札を見て、目が飛び出るほど驚いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目がない",
    "japanese": "そのことが非常に好きである。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "姉は甘いものに目がない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目が回る",
    "japanese": "とても忙しい。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "目が回るような一日。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "目先が利く",
    "japanese": "先の見通しが確かだ。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "彼は目先が利くので、商売がうまい。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目と鼻の先",
    "japanese": "二つの場所がとても近くにあること。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "学校は家から目と鼻の先にある。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目に余る",
    "japanese": "あまりにひどくて見過ごせない。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "彼のわがままは目に余る。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目に入れても痛くない",
    "japanese": "かわいくてたまらない。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "祖父は孫が目に入れても痛くないほどかわいいらしい。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目に浮かぶ",
    "japanese": "様子が想像できる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "手紙を読むと、故郷の風景が目に浮かぶ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目に物見せる",
    "japanese": "ひどい目にあわせて思い知らせる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "次こそは勝って、目に物見せてやる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目の色を変える",
    "japanese": "気持ちの変化で表情を変える。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "試験が迫り、目の色を変えて勉強する。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "目のかたきにする",
    "japanese": "何かあるたびに憎く思う。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "なぜか彼は私を目のかたきにしている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目の毒",
    "japanese": "見ると欲しくなるので、見ないほうがいい物。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "ショーウインドウの新製品は目の毒だ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目もくれない",
    "japanese": "見向きもしない。無関心である。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "彼は寄り道にも目もくれず家へ帰った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目も当てられない",
    "japanese": "ひどくて見ていられない。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "部屋は散らかり放題で、目も当てられない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を奪われる",
    "japanese": "素晴らしさに驚き、夢中になる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "満開の桜に目を奪われた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目をかける",
    "japanese": "ひいきにする。親切に世話する。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "監督は若い選手に目をかけている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目をこらす",
    "japanese": "一点をじっと見つめる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "暗がりの中、目をこらして相手を探した。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を皿にする",
    "japanese": "よく見ようとして目を大きく開く。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "落とした指輪を、目を皿にして探した。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を三角にする",
    "japanese": "激しく怒る様子。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "母は弟のいたずらに目を三角にして怒った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を通す",
    "japanese": "ひととおり見る。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "提出前に、書類にもう一度目を通す。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を留める",
    "japanese": "気がついたものをじっと見る。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "一枚の絵に目を留めて足を止めた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を光らす",
    "japanese": "油断なく見張る。監視する。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "先生が目を光らせているので、私語はできない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を引く",
    "japanese": "周囲の注目を集める。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "派手な看板が通行人の目を引いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を細める",
    "japanese": "うれしさやかわいさでほほ笑む。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "母は子の成長に目を細めた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "目を丸くする",
    "japanese": "驚きのため、目を大きく見開く。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "突然の合格発表に、みんな目を丸くした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "瞳をこらす",
    "japanese": "じっと見つめる。",
    "yomi": "",
    "category": "目",
    "superCategory": "からだに関する慣用句",
    "example": "星空に瞳をこらすと、天の川が見えてきた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "耳が痛い",
    "japanese": "自分の弱点を言われ、聞くのがつらい。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "だらしないと注意され、耳が痛い話だった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "耳にたこができる",
    "japanese": "何度も聞いてうんざりする。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "その自慢話は、耳にたこができるほど聞いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "耳を疑う",
    "japanese": "思いもよらぬことで信じられない。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "突然の知らせに、思わず耳を疑った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "耳を貸す",
    "japanese": "相手の話を聞く。相談にのる。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "彼の学説に耳を貸す者は少なかった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "耳を澄ます",
    "japanese": "聞くことに集中する（=耳を傾ける）。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "耳を澄ますと、小川のせせらぎが聞こえた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "耳をそろえる",
    "japanese": "金額などを不足なくとりそろえる。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "借りたお金を、耳をそろえて返した。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "小耳に挟む",
    "japanese": "聞くともなしに聞く。偶然聞く。",
    "yomi": "",
    "category": "耳",
    "superCategory": "からだに関する慣用句",
    "example": "友人のうわさを小耳に挟んだ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "肝がすわる",
    "japanese": "何があっても落ち着いている。",
    "yomi": "",
    "category": "肝",
    "superCategory": "からだに関する慣用句",
    "example": "彼は肝がすわっていて、大舞台でも動じない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肝に銘じる",
    "japanese": "心にきざみこんで忘れない。",
    "yomi": "",
    "category": "肝",
    "superCategory": "からだに関する慣用句",
    "example": "先生の言葉を肝に銘じて努力する。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肝を冷やす",
    "japanese": "あぶない目にあってひやっとする。",
    "yomi": "",
    "category": "肝",
    "superCategory": "からだに関する慣用句",
    "example": "車が急に飛び出してきて肝を冷やした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肝をつぶす",
    "japanese": "非常に驚く。",
    "yomi": "",
    "category": "肝",
    "superCategory": "からだに関する慣用句",
    "example": "突然の大きな物音に肝をつぶした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肩で風を切る",
    "japanese": "威勢がよくて得意な態度を見せる。",
    "yomi": "",
    "category": "肩",
    "superCategory": "からだに関する慣用句",
    "example": "優勝した選手は、肩で風を切って歩いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肩の荷が下りる",
    "japanese": "負担や責任から解放される。",
    "yomi": "",
    "category": "肩",
    "superCategory": "からだに関する慣用句",
    "example": "発表が無事に終わり、肩の荷が下りた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肩を入れる",
    "japanese": "力をそえる。ひいきにする。",
    "yomi": "",
    "category": "肩",
    "superCategory": "からだに関する慣用句",
    "example": "監督は新人の育成に肩を入れている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "肩をすくめる",
    "japanese": "どうしようもない気持ちを表す。",
    "yomi": "",
    "category": "肩",
    "superCategory": "からだに関する慣用句",
    "example": "予想外の配役に、友人は肩をすくめた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "肩を並べる",
    "japanese": "対等に張り合う。",
    "yomi": "",
    "category": "肩",
    "superCategory": "からだに関する慣用句",
    "example": "努力を重ね、ついに強豪校と肩を並べた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸が痛む",
    "japanese": "悲しくてつらい。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "過去の悲劇に胸が痛む。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "胸がいっぱいになる",
    "japanese": "感動で心が満たされる。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "温かい言葉に、胸がいっぱいになった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸が躍る",
    "japanese": "喜びや期待で心がわくわくする。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "明日の遠足を思うと胸が躍る。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸がしめつけられる",
    "japanese": "せつなさを覚える。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "別れの場面に胸がしめつけられた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸がすく",
    "japanese": "気持ちがすっきりする。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "チームの初勝利に、胸がすく思いがした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "胸が迫る",
    "japanese": "強い感情が心の中に満ちる。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "感動的な結末に胸が迫った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸を打つ",
    "japanese": "感動を強くあたえる。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "彼女の生き方は、多くの人の胸を打った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸をこがす",
    "japanese": "恋い慕って思い悩む。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "かなわぬ恋に胸をこがす。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸をつかれる",
    "japanese": "はっとして驚く。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "彼女のするどい指摘に胸をつかれた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "胸をなでおろす",
    "japanese": "ほっと安心する。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "無事の知らせに胸をなでおろした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸をはずませる",
    "japanese": "期待でわくわくする。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "初めての海外旅行に胸をはずませる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "胸を張る",
    "japanese": "自信に満ちた態度を取る。",
    "yomi": "",
    "category": "胸",
    "superCategory": "からだに関する慣用句",
    "example": "全力を出したので、負けても胸を張れる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "脇が甘い",
    "japanese": "すきがあり、守りが弱い。",
    "yomi": "",
    "category": "脇",
    "superCategory": "からだに関する慣用句",
    "example": "相撲で脇に腕を差し込まれると不利になることから。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "腕が立つ",
    "japanese": "技術や能力がすぐれている。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "彼は料理の腕が立つ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腕が鳴る",
    "japanese": "力を発揮したくて、じっとしていられない。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "大会を前にして腕が鳴る。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腕によりをかける",
    "japanese": "気持ちをこめて、能力を発揮する。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "母は腕によりをかけて料理を作った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腕を上げる",
    "japanese": "上手になる。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "毎日の練習で、ずいぶん腕を上げた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腕を振るう",
    "japanese": "能力を使って、見事にやってみせる。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "得意の料理で腕を振るう。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腕を磨く",
    "japanese": "勉強や練習に励み、実力や技術を高める。",
    "yomi": "",
    "category": "腕",
    "superCategory": "からだに関する慣用句",
    "example": "一流をめざして、日々腕を磨く。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腰を据える",
    "japanese": "じっくりかまえる。",
    "yomi": "",
    "category": "腰",
    "superCategory": "からだに関する慣用句",
    "example": "腰を据えて研究に取り組む。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腰を抜かす",
    "japanese": "驚きで足腰が立たなくなる。",
    "yomi": "",
    "category": "腰",
    "superCategory": "からだに関する慣用句",
    "example": "あまりの恐ろしさに腰を抜かした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腰が重い",
    "japanese": "なかなか動こうとしない。",
    "yomi": "",
    "category": "腰",
    "superCategory": "からだに関する慣用句",
    "example": "兄は腰が重く、なかなか勉強を始めない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腹が黒い",
    "japanese": "心の中がきたない。根性が悪い。",
    "yomi": "",
    "category": "腹",
    "superCategory": "からだに関する慣用句",
    "example": "笑顔の裏で、彼は意外に腹が黒い。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腹に据えかねる",
    "japanese": "怒りをおさえることができない。",
    "yomi": "",
    "category": "腹",
    "superCategory": "からだに関する慣用句",
    "example": "度重なる無礼に、ついに腹に据えかねた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腹をさぐる",
    "japanese": "人の気持ちをそれとなくうかがう。",
    "yomi": "",
    "category": "腹",
    "superCategory": "からだに関する慣用句",
    "example": "相手の腹をさぐりながら話を進めた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "腹を割る",
    "japanese": "本当の気持ちを打ち明ける。",
    "yomi": "",
    "category": "腹",
    "superCategory": "からだに関する慣用句",
    "example": "一度、腹を割って話し合おう。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "小腹が立つ",
    "japanese": "ちょっとしゃくにさわる。",
    "yomi": "",
    "category": "腹",
    "superCategory": "からだに関する慣用句",
    "example": "生意気な返事に、少し小腹が立った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "膝を打つ",
    "japanese": "何か思いついたり感心したりしたときの動作。",
    "yomi": "",
    "category": "膝",
    "superCategory": "からだに関する慣用句",
    "example": "うまい考えに、思わず膝を打った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足が出る",
    "japanese": "予算が不足する。赤字になる。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "予定より買いすぎて、足が出てしまった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足が向く",
    "japanese": "知らず知らずにその方へ行く。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "気づくと、なじみの店に足が向いていた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足を洗う",
    "japanese": "悪いことをやめてまじめになる。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "悪い仲間から足を洗って、まじめに働く。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足をすくう",
    "japanese": "相手のすきにつけいる。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "油断していると、足をすくわれる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足を運ぶ",
    "japanese": "歩いて行く。わざわざ訪ねて行く。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "何度も足を運んで、ようやく話がまとまった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足を引っぱる",
    "japanese": "他人のじゃまをする。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "味方の足を引っぱらないよう努力する。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "足を棒にする",
    "japanese": "足がひどく疲れるほど歩き回る。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "いなくなった子犬を足を棒にして捜し回る。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "きびすを返す",
    "japanese": "来た道を引き返す。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "忘れ物に気づき、きびすを返して取りに戻る。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "二の足を踏む",
    "japanese": "思い切れずにためらう。",
    "yomi": "",
    "category": "足",
    "superCategory": "からだに関する慣用句",
    "example": "値段が高くて、買うのに二の足を踏んだ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "股にかける",
    "japanese": "広い範囲で活動する。",
    "yomi": "",
    "category": "身",
    "superCategory": "からだに関する慣用句",
    "example": "世界を股にかけて活躍する商人だ。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "身につまされる",
    "japanese": "人の不幸を自分のことのように感じる。",
    "yomi": "",
    "category": "身",
    "superCategory": "からだに関する慣用句",
    "example": "同じ境遇の話に、身につまされた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "身にしみる",
    "japanese": "しみじみと心に感じる。",
    "yomi": "",
    "category": "身",
    "superCategory": "からだに関する慣用句",
    "example": "親のありがたさが身にしみる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "身の毛がよだつ",
    "japanese": "ぞっとする。",
    "yomi": "",
    "category": "身",
    "superCategory": "からだに関する慣用句",
    "example": "身の毛がよだつような怪談を聞いた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "身を粉にする（身を入れる）",
    "japanese": "一生懸命になる。",
    "yomi": "",
    "category": "身",
    "superCategory": "からだに関する慣用句",
    "example": "家族のために、身を粉にして働く。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "頭が上がらない",
    "japanese": "相手に弱みがあり、対等になれない。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "世話になった先生には頭が上がらない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "頭がかたい",
    "japanese": "柔軟な考え方ができない。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "頭がかたい人は、新しい考えを受け入れにくい。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "頭が下がる",
    "japanese": "本当に偉いと感心させられる。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "彼のひたむきな努力には頭が下がる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "頭にくる",
    "japanese": "かっとする。つい怒る。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "約束を破られて頭にきた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "頭をかかえる",
    "japanese": "考え込む。思案・苦慮する。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "難しい問題に頭をかかえた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔から火が出る",
    "japanese": "恥ずかしさで顔が真っ赤になる。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "みんなの前で転んで、顔から火が出る思いだった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔が売れる",
    "japanese": "有名になる。広く世に知られる。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "テレビに出て、すっかり顔が売れた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔が立つ",
    "japanese": "名誉が保たれる。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "君のおかげで、私の顔が立った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔が広い",
    "japanese": "知り合いが多い。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "父は顔が広く、知り合いが多い。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔にどろを塗る",
    "japanese": "人に恥をかかせる。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "勝手な行いは、親の顔にどろを塗ることになる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "顔を出す",
    "japanese": "人前に出る。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "忙しくても、会合には顔を出すようにしている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "大きな顔をする",
    "japanese": "いばる。得意がる。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "少し勝ったくらいで大きな顔をするな。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "涼しい顔",
    "japanese": "自分には関係ないという態度。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "彼は涼しい顔でうそをついている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "つらの皮が厚い",
    "japanese": "厚かましい。ずうずうしい。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "何度断られても平気とは、つらの皮が厚い。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "臆面もなく",
    "japanese": "恥知らずでずうずうしく。",
    "yomi": "",
    "category": "顔",
    "superCategory": "からだに関する慣用句",
    "example": "遅刻したのに、臆面もなく笑っている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "骨が折れる",
    "japanese": "苦労や努力がいる。困難である。",
    "yomi": "",
    "category": "骨",
    "superCategory": "からだに関する慣用句",
    "example": "慣れない作業は骨が折れる。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "骨（身）を惜しむ",
    "japanese": "苦労をいやがってなまけること。",
    "yomi": "",
    "category": "骨",
    "superCategory": "からだに関する慣用句",
    "example": "骨を惜しまず働きなさい。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "鼻が高い",
    "japanese": "得意な様子。自慢げである。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "弟が優勝して、兄として鼻が高い。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鼻で笑う",
    "japanese": "馬鹿にして笑う。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "私の意見を、彼は鼻で笑った。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鼻にかける",
    "japanese": "自慢する。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "彼は成績のよさを鼻にかけている。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鼻もちならない",
    "japanese": "態度がきざで、我慢できない。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "気取った態度が鼻もちならない。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鼻を明かす",
    "japanese": "出し抜いて、あっと言わせる。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "実力で勝って、ライバルの鼻を明かした。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鼻を折る",
    "japanese": "相手の自慢をくじく。恥をかかせる。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "生意気な相手の鼻を折ってやった。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": true
  },
  {
    "english": "木で鼻をくくる",
    "japanese": "冷淡にあしらう。",
    "yomi": "",
    "category": "鼻",
    "superCategory": "からだに関する慣用句",
    "example": "木で鼻をくくったような態度で断られた。",
    "exampleJapanese": "",
    "bigCategory": "からだに関する慣用句",
    "exampleAI": false
  },
  {
    "english": "まゆをひそめる",
    "japanese": "いやな顔をする。",
    "yomi": "",
    "category": "まゆ",
    "superCategory": "からだに関する慣用句",
    "example": "下品な言葉に、周りの人がまゆをひそめた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "まゆにつばをぬる",
    "japanese": "だまされないように用心する。",
    "yomi": "",
    "category": "まゆ",
    "superCategory": "からだに関する慣用句",
    "example": "うますぎる話には、まゆにつばをぬったほうがいい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "喉から手が出る",
    "japanese": "欲しくて我慢できない。",
    "yomi": "",
    "category": "喉",
    "superCategory": "からだに関する慣用句",
    "example": "喉から手が出るほど、その本が欲しい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "奥歯にものが挟まる",
    "japanese": "何か隠して言いにくそうな様子。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "奥歯にものが挟まったような言い方はやめてほしい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "歯が浮く",
    "japanese": "見えすいたお世辞などで不快になる。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "歯が浮くようなお世辞を言われた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "歯が立たない",
    "japanese": "相手が強すぎて対抗できない。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "相手が強すぎて、まるで歯が立たない。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "歯がゆい",
    "japanese": "思い通りにならず、もどかしい。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "思うように上達せず、歯がゆい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "歯切れがよい",
    "japanese": "言葉をはっきり言う様子。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "彼の返事は、いつも歯切れがよい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "歯に衣着せぬ",
    "japanese": "言いにくいことでも遠慮なく言う。",
    "yomi": "",
    "category": "歯",
    "superCategory": "からだに関する慣用句",
    "example": "彼は歯に衣着せぬ物言いで知られている。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "舌を巻く",
    "japanese": "非常に驚き、感嘆する。",
    "yomi": "",
    "category": "舌",
    "superCategory": "からだに関する慣用句",
    "example": "見事な演奏に、審査員も舌を巻いた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "額を集める",
    "japanese": "顔を近づけて相談する。",
    "yomi": "",
    "category": "頬",
    "superCategory": "からだに関する慣用句",
    "example": "みんなで額を集めて対策を練った。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "頬を染める",
    "japanese": "はじらいのため、頬を赤くする。",
    "yomi": "",
    "category": "頬",
    "superCategory": "からだに関する慣用句",
    "example": "ほめられて、彼女は頬を染めた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "頬をふくらます",
    "japanese": "不満そうな顔をする。",
    "yomi": "",
    "category": "頬",
    "superCategory": "からだに関する慣用句",
    "example": "妹はしかられて、頬をふくらませた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "かぶりを振る",
    "japanese": "認めないという意味で頭を振る。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "私の提案に彼はかぶりを振った。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": false
  },
  {
    "english": "怒り心頭に発する",
    "japanese": "はげしい怒りがこみあげる。",
    "yomi": "",
    "category": "頭",
    "superCategory": "からだに関する慣用句",
    "example": "裏切りを知って、怒り心頭に発した。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "顎が落ちる",
    "japanese": "料理の味が非常にいいこと。",
    "yomi": "",
    "category": "顎",
    "superCategory": "からだに関する慣用句",
    "example": "このケーキは、顎が落ちるほどおいしい。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "顎で使う",
    "japanese": "いばった態度で人に指図する。",
    "yomi": "",
    "category": "顎",
    "superCategory": "からだに関する慣用句",
    "example": "人を顎で使うような態度は感心しない。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "顎を出す",
    "japanese": "ひどく疲れる。ばてる。",
    "yomi": "",
    "category": "顎",
    "superCategory": "からだに関する慣用句",
    "example": "きつい練習に、さすがに顎を出した。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "首をかしげる",
    "japanese": "不審に思う。",
    "yomi": "",
    "category": "首",
    "superCategory": "からだに関する慣用句",
    "example": "政治家の説明に首をかしげる。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": false
  },
  {
    "english": "首をすくめる",
    "japanese": "驚きや恐れで、思わず首を縮める。",
    "yomi": "",
    "category": "首",
    "superCategory": "からだに関する慣用句",
    "example": "いきなりの轟音に、皆が首をすくめた。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": false
  },
  {
    "english": "首を長くする",
    "japanese": "今か今かと待ちわびる。",
    "yomi": "",
    "category": "首",
    "superCategory": "からだに関する慣用句",
    "example": "合格発表を、首を長くして待つ。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": true
  },
  {
    "english": "首をひねる",
    "japanese": "考え込む。納得できずにいる。",
    "yomi": "",
    "category": "首",
    "superCategory": "からだに関する慣用句",
    "example": "弟の不可解な話に私は首をひねった。",
    "exampleJapanese": "",
    "bigCategory": "顔・頭の近くの部分",
    "exampleAI": false
  },
  {
    "english": "蟻のはい出る隙もない",
    "japanese": "警備・警戒が厳しい様子。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "お祭りの会場は警察官だらけで、蟻のはい出る隙もなかった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "牛の歩み",
    "japanese": "進み具合の遅いこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "工事は牛の歩みのようになかなか進まない。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鵜の目鷹の目",
    "japanese": "見逃すまいと熱心に探す様子。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "先生は鵜の目鷹の目でカンニングがないか見張っている。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鵜のみにする",
    "japanese": "物事を考えないで受け入れる。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "友達の話を鵜のみにして、だまされてしまった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "馬が合う",
    "japanese": "自分と考えが合う。意気投合する。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "初めて会ったのに、すぐに馬が合った。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "尻尾を出す",
    "japanese": "ごまかしや隠しごとがばれる。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "うそをついていたが、ついに尻尾を出してしまった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "蚊の鳴くような声",
    "japanese": "元気のないとても小さな声。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "緊張して、蚊の鳴くような声しか出なかった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "烏の行水",
    "japanese": "とても短い時間で入浴を済ませること。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "弟はいつも烏の行水で、すぐにお風呂から出てくる。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "閑古鳥が鳴く",
    "japanese": "店などにほとんどお客がいない様子。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "雨の日の遊園地は閑古鳥が鳴いていた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "狐につままれる",
    "japanese": "わけがわからずぽかんとする。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "突然テストが中止になり、狐につままれたような気分だった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "牙をむく",
    "japanese": "敵意をあらわにする。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "おとなしかった犬が急に牙をむいた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "蜘蛛の子を散らす",
    "japanese": "散らばって逃げる。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "サイレンが鳴ると、人々は蜘蛛の子を散らすように逃げた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "犬猿の仲",
    "japanese": "仲が悪いこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "あの二人は犬猿の仲で、いつもけんかしている。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鯖を読む",
    "japanese": "自分の都合のいいように数量をごまかす。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "年齢を鯖を読んで、三つも若く言った。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "尻馬に乗る",
    "japanese": "よく考えないで、人に従って行動する。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "友達の尻馬に乗って、自分も悪口を言ってしまった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "雀の涙",
    "japanese": "量がきわめて少ないこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "アルバイトの給料は雀の涙ほどだった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "狸寝入り",
    "japanese": "眠ったふりをすること。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "弟は狸寝入りをして、宿題から逃げようとした。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鶴の一声",
    "japanese": "有力者の一言で議論がまとまること。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "結局、会長の鶴の一声で決まった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "飛ぶ鳥を落とす勢い",
    "japanese": "たいへん勢いが盛んな様子。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "そのアイドルグループは飛ぶ鳥を落とす勢いで人気が出た。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "鳶に油揚げをさらわれる",
    "japanese": "大事なものを不意に奪われる。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "せっかく見つけた席を、鳶に油揚げをさらわれるように取られた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "虎の子",
    "japanese": "大切にして手放さないもの。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "虎の子の貯金をはたいて、新しい自転車を買った。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "猫なで声",
    "japanese": "やさしくこびる声。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "何かお願いがあるのか、妹が猫なで声で話しかけてきた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "猫の手も借りたい",
    "japanese": "とても忙しい。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "年末の大掃除は猫の手も借りたいほど忙しかった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "猫の額",
    "japanese": "非常に狭いこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "うちの庭は猫の額ほどの広さしかない。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "猫も杓子も",
    "japanese": "だれもかれもみんな。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "最近は猫も杓子もスマートフォンを持っている。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "猫をかぶる",
    "japanese": "本性を隠し、おとなしいふりをする。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "彼女は先生の前では猫をかぶっている。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "羽を伸ばす",
    "japanese": "のびのびと自由にふるまう。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "試験が終わって、友達と羽を伸ばして遊んだ。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "袋のねずみ",
    "japanese": "追いつめられて逃げられないこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "行き止まりに追い込まれて、もう袋のねずみだ。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "虫がいい",
    "japanese": "自分勝手で人の都合を考えない。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "手伝わないのにごほうびだけほしいなんて、虫がいい話だ。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "虫が知らせる",
    "japanese": "なんとなく悪い予感がする。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "虫が知らせるものがあって、家に電話をかけた。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "虫が好かない",
    "japanese": "何となく好きになれない。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "理由はないけれど、あの人はどうも虫が好かない。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "やぶへび",
    "japanese": "余計なことをして災難にあうこと。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "余計なことを言ったせいで、やぶへびになってしまった。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "わしづかみ",
    "japanese": "乱暴につかみとること。",
    "yomi": "",
    "category": "動物",
    "superCategory": "動植物に関する慣用句",
    "example": "彼の演奏は観客の心をわしづかみにした。",
    "exampleJapanese": "",
    "bigCategory": "動物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "瓜二つ",
    "japanese": "そっくりなこと。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "あの双子は瓜二つで、見分けがつかない。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "ごぼう抜き",
    "japanese": "競走などで一気に何人も追い抜くこと。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "最後の直線で五人をごぼう抜きにした。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "高嶺の花",
    "japanese": "力がおよばず、手に入れられないもの。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "あの有名な絵は高嶺の花で、とても買えない。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "竹を割ったよう",
    "japanese": "さっぱりしていてこだわらない様子。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "彼は竹を割ったような性格で、みんなに好かれている。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "梨のつぶて",
    "japanese": "なんの返事も連絡もないこと。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "メールを送ったのに梨のつぶてで、返事がない。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "根に持つ",
    "japanese": "うらむ気持ちをいつまでも忘れない。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "あの人は昔のことをいつまでも根に持っている。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "根掘り葉掘り",
    "japanese": "細かいことをしつこくたずねる様子。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "母に根掘り葉掘り質問された。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "根も葉もない",
    "japanese": "まったく根拠がない。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "そんな根も葉もないうわさを信じてはいけない。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "根を下ろす",
    "japanese": "新しい思想やものごとなどが定着する。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "この町に引っ越してきて、ようやく根を下ろした。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "根を張る",
    "japanese": "深く広がり、動かしがたくなっている。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "その悪い習慣は社会に深く根を張っている。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "花を咲かせる",
    "japanese": "①にぎやかにする。②栄える。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "①なつかしい思い出話に花を咲かせる。②この芝居で、彼も花を咲かせることができた。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "花を添える",
    "japanese": "はなやかさを加える。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "優勝パーティーに有名人が出席して花を添えた。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "花を持たせる",
    "japanese": "名誉を相手にゆずる。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "年長者に花を持たせる。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "道草を食う",
    "japanese": "目的地への途中で別のことをする。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "学校の帰りに道草を食って遅くなった。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "実を結ぶ",
    "japanese": "良い結果を生む。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "毎日の練習がついに実を結んで、優勝できた。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "柳に風",
    "japanese": "相手に逆らわないで軽くあしらうこと。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "彼は文句を言われても柳に風と受け流す。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "やぶから棒",
    "japanese": "出しぬけに。急に。",
    "yomi": "",
    "category": "草花",
    "superCategory": "動植物に関する慣用句",
    "example": "やぶから棒に質問されて、びっくりした。",
    "exampleJapanese": "",
    "bigCategory": "植物に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "言葉に余る",
    "japanese": "言葉では言い尽くすことができない。",
    "yomi": "",
    "category": "言葉",
    "superCategory": "その他の慣用句",
    "example": "感謝の気持ちは、言葉に余るほどだ。",
    "exampleJapanese": "",
    "bigCategory": "言葉に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "言葉に詰まる",
    "japanese": "返事ができずに困る。",
    "yomi": "",
    "category": "言葉",
    "superCategory": "その他の慣用句",
    "example": "彼に気持ちを聞かれ、言葉に詰まった。",
    "exampleJapanese": "",
    "bigCategory": "言葉に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "言葉を尽くす",
    "japanese": "多くの言葉を使って話す。",
    "yomi": "",
    "category": "言葉",
    "superCategory": "その他の慣用句",
    "example": "言葉を尽くして説明したが、わかってもらえなかった。",
    "exampleJapanese": "",
    "bigCategory": "言葉に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "言葉を濁す",
    "japanese": "はっきりと言わず、あいまいにする。",
    "yomi": "",
    "category": "言葉",
    "superCategory": "その他の慣用句",
    "example": "都合が悪いのか、彼は言葉を濁した。",
    "exampleJapanese": "",
    "bigCategory": "言葉に関する慣用句",
    "exampleAI": true
  },
  {
    "english": "言葉を挟む",
    "japanese": "人の話に口出しする。",
    "yomi": "",
    "category": "言葉",
    "superCategory": "その他の慣用句",
    "example": "横から言葉を挟む。",
    "exampleJapanese": "",
    "bigCategory": "言葉に関する慣用句",
    "exampleAI": false
  },
  {
    "english": "相づちを打つ",
    "japanese": "相手の話に合わせて受け答えをする。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "話を聞きながら、うなずいて相づちを打つ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "挙げ句の果て",
    "japanese": "ものごとの最後。結局。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "さんざん迷った挙げ句の果て、何も買わなかった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "後の祭り",
    "japanese": "時機をのがし、手遅れになること。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "今さら悔やんでも、後の祭りだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "油を売る",
    "japanese": "むだな話などで時間をつぶしてなまける。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "使いの途中で油を売っていて、しかられた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "油をしぼる",
    "japanese": "過ちを強く責める。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "帰りが遅くなって父に油をしぼられた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "嵐の前の静けさ",
    "japanese": "さわぎが起こる前の不気味な静けさ。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "試合前の会場は、嵐の前の静けさのようだった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "泡を食う",
    "japanese": "ひどく驚きあわてる。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "突然の呼び出しに、泡を食って駆けつけた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "暗礁に乗り上げる",
    "japanese": "会議や交渉などのついてに行き詰まる。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "話し合いは意見の対立で、暗礁に乗り上げた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "行きがけの駄賃",
    "japanese": "あることのついでに他のことをすること。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "買い物の行きがけの駄賃に、手紙も出してきた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "息が詰まる",
    "japanese": "緊張などから息苦しくなる。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "静まりかえった会場で、息が詰まりそうだった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "息を切らす",
    "japanese": "せわしく呼吸をする。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "坂道を登って、息を切らして到着した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "息を殺す",
    "japanese": "息をおさえて、じっと静かにしている。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "物音を立てぬよう、息を殺してひそんだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "息を呑む",
    "japanese": "驚きのあまり息ができない。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "初めて海で出会うイルカの姿に、息をのんだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "息を潜める",
    "japanese": "ひっそりと静かにしている。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "猫は獲物をねらって息を潜めていた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "息を吹き返す",
    "japanese": "悪い状態を脱し、よい状態に向かう。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "資金援助で、会社は息を吹き返した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "板につく",
    "japanese": "職業や地位などになじむ。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "司会も、すっかり板についてきた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "一目を置く",
    "japanese": "相手の力を認め、敬意をもつ。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "囲碁で弱いほうが先に碁石を置くことから。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "一杯食う",
    "japanese": "うまくだまされてしまう。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "まんまと敵の作戦に一杯食った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "色を失う",
    "japanese": "驚いて顔が青くなる。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "突然の悪い知らせに、みな色を失った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "裏表がない",
    "japanese": "どこでも同じ態度で接する様子。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "あの人は裏表がない、信用できる人だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "裏をかく",
    "japanese": "相手が予想しない行動に出る。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "相手の裏をかいて、逆方向へ走った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "うわの空",
    "japanese": "他のことが気になり、注意が向かない様子。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "心配事があるのか、彼は授業中もうわの空だった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "英気を養う",
    "japanese": "次の働きに向けて十分に休養を取る。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "週末はゆっくり休んで英気を養う。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "襟を正す",
    "japanese": "今までの態度を改めて気を引き締める。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "校長の話に、生徒たちは襟を正して聞いた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "お茶を濁す",
    "japanese": "いい加減にして、その場を繕う。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "都合の悪い質問には、笑ってお茶を濁した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "同じ土俵",
    "japanese": "同じ分野。近い立場。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "同じ土俵で戦う。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "尾を引く",
    "japanese": "後まで影響が残る。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "けんかのしこりが、いつまでも尾を引いた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "思うつぼ",
    "japanese": "予期した状態。",
    "yomi": "",
    "category": "その他あ行",
    "superCategory": "その他の慣用句",
    "example": "ここであきらめたら、敵の思うつぼだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "影が薄い",
    "japanese": "存在が目立たない。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "おとなしい彼は、クラスでも影が薄い。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "影を潜める",
    "japanese": "おもてに出なくなる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "一時流行した遊びも、最近は影を潜めた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "笠に着る",
    "japanese": "力のある人に頼っていばる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "親の力を笠に着て、いばっている。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "風の便り",
    "japanese": "どこからともなく伝わってくるうわさ。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "風の便りに、旧友の活躍を聞いた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "固唾をのむ",
    "japanese": "緊張してことの成り行きを見守る。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "固唾をのんで合否の結果発表を見守る。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "肩を持つ",
    "japanese": "ひいきにする。味方をする。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "妹は、いつも弟の肩を持つ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "株が上がる",
    "japanese": "周囲からの評価が高くなる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "文化祭の発表で、吹奏楽部の株が上がった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "片棒をかつぐ",
    "japanese": "（悪い）計画に加わり力をかす。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "知らぬ間に、悪事の片棒をかつがされていた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "角が立つ",
    "japanese": "人間関係がぎこちないものになる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "はっきり言いすぎると角が立つ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "かぶとを脱ぐ",
    "japanese": "降参する。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "彼の熱意には、さすがにかぶとを脱いだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "鎌を掛ける",
    "japanese": "聞きたいことを自ら言うようにしむける。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "鎌を掛けたら、うっかり本当のことを白状した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "殻に閉じこもる",
    "japanese": "自分の世界にこもり心を開かない。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "失敗して以来、殻に閉じこもってしまった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "堪忍袋の緒が切れる",
    "japanese": "がまんができなくなる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "度重なるいたずらに、ついに堪忍袋の緒が切れた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "間髪をいれず",
    "japanese": "すぐに。間を置かずに。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "質問に間髪をいれず答える。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "気が置けない",
    "japanese": "気遣いがいらない。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "「油断ができない」という意味ではない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "きまりが悪い",
    "japanese": "はずかしい。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "うそがばれて、きまりが悪い思いをした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "気が気でない",
    "japanese": "心配のために心が落ち着かない。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "明日の試合のことを思うと、気が気でない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "気が早い",
    "japanese": "せっかちだ。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "まだ夏なのに冬服の話とは、気が早い。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "気が重い",
    "japanese": "憂鬱な気分になる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "雨の日が続くと気がめいってしまう。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "気がもめる（気をもむ）",
    "japanese": "心配で、心が落ち着かない。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "結果がなかなか出ず、気がもめる。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "気にくわない",
    "japanese": "不満だ。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "彼のなれなれしい態度が気にくわない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "気を配る",
    "japanese": "周囲にこまかく注意を払う。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "客が快適に過ごせるよう、細かく気を配る。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "琴線に触れる",
    "japanese": "人の心の奥に触れ、感動をあたえる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "その一言が、彼の琴線に触れた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "釘を刺す",
    "japanese": "後で問題が生じないように念を押す。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "遅刻しないよう、前もって釘を刺しておいた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "軍配が上がる",
    "japanese": "どちらか一方の勝ちが決定する。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "熱戦の末、赤組に軍配が上がった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "警鐘を鳴らす",
    "japanese": "危険な状態であることを知らせる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "専門家は環境破壊に警鐘を鳴らしている。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "桁が違う",
    "japanese": "程度や数量にたいへん違いがある。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "彼の実力は、私たちとは桁が違う。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "煙を立てる",
    "japanese": "生計を立てる。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "わずかな収入で、なんとか煙を立てている。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "けりがつく",
    "japanese": "決着がつく。",
    "yomi": "",
    "category": "その他か行",
    "superCategory": "その他の慣用句",
    "example": "和歌・俳句の最後に「けり」を使うことから。紛争にけりがつく。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "さじを投げる",
    "japanese": "実現させるのが不可能な物事をあきらめる。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "医者もさじを投げるほどの難病だった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "じだんだを踏む",
    "japanese": "くやしくて足ぶみをする。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "先を越され、じだんだを踏んで悔しがる。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "しのぎを削る",
    "japanese": "お互いに激しく競い合う。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "「しのぎ」とは、刀の刃と峰の中間の少し盛り上がった部分のこと。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "しびれを切らす",
    "japanese": "待ちきれなくなる。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "待ち合わせ相手が来ず、しびれを切らした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "重箱の隅を楊枝でほじくる（つつく）",
    "japanese": "細かいことまで突き止めたり、指摘したりする。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "重箱の隅を楊枝でほじくるような、細かい注意ばかりだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "雌雄を決する",
    "japanese": "どちらが強いかを決める。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "決勝戦で、両校が雌雄を決する。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "数珠つなぎ",
    "japanese": "連続して連なっていること。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "入場者が数珠つなぎに並んでいる。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "しらを切る",
    "japanese": "知っていても知らないふりをする。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "証拠があるのに、彼はしらを切り続けた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "心血を注ぐ",
    "japanese": "全力をあげて何かに取り組む。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "研究に心血を注いだ成果が実った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "砂をかむよう",
    "japanese": "何のおもしろみもない。味気ない。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "一人きりの食事は、砂をかむようだった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "図に乗る",
    "japanese": "いい気になる。つけあがる。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "ほめられて図に乗り、調子に乗りすぎた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "隅に置けない",
    "japanese": "あなどれない。抜け目がない。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "彼は、なかなか隅に置けない人物だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "精を出す",
    "japanese": "熱心に働く。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "部活の練習に精を出す。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "精も根も尽きる（果てる）",
    "japanese": "力を出しきって、気力がなくなる。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "三日間の大会の運営で、精も根も尽きた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "せきを切ったように",
    "japanese": "おさえられていたものが、勢いよく動きだす様子。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "彼女はせきを切ったように話し始めた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "底をつく",
    "japanese": "貯えがなくなる。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "旅の費用が、とうとう底をついた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "反りが合わない",
    "japanese": "仲がよくない。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "あの二人は、どうも反りが合わない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "世間ずれ",
    "japanese": "実社会で苦労して、ずるくなること。",
    "yomi": "",
    "category": "その他さ行",
    "superCategory": "その他の慣用句",
    "example": "苦労してきた彼は、少し世間ずれしている。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "太鼓判を押す",
    "japanese": "まちがいのないことを保証する。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "品質は私が太鼓判を押します。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "高みの見物",
    "japanese": "安全な場所で何もせずに見ていること。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "人の苦労を高みの見物とは、ひどい。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "高をくくる",
    "japanese": "大したことはないだろうと見くびる。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "簡単だと高をくくって、痛い目にあった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "立て板に水",
    "japanese": "すらすらとよどみなく話す様子。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "彼女は立て板に水のように話す。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "棚に上げる",
    "japanese": "わざと触れずにすます。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "自分のことは棚に上げて、人を責める。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "力を落とす",
    "japanese": "がっかりして意欲が減退する。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "不合格の知らせに、彼はすっかり力を落とした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "力を貸す",
    "japanese": "手助けする。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "困っている友に力を貸す。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "つじつまが合う",
    "japanese": "筋道が通っている。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "話のつじつまが合わず、うそが見破られた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "途方に暮れる",
    "japanese": "どうすればいいかわからなくて困る。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "道に迷い、途方に暮れた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "取りつく島もない",
    "japanese": "冷淡で相手にしてくれない。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "忙しいと断られ、取りつく島もなかった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "取るに足らない",
    "japanese": "取り上げるだけの価値がない。",
    "yomi": "",
    "category": "その他た行",
    "superCategory": "その他の慣用句",
    "example": "そんな取るに足らないことで悩むな。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "流れに棹さす",
    "japanese": "全体の勢いに乗り、さらに進める。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "「流れに逆らう」の意味で使うのは誤り。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "煮え切らない",
    "japanese": "はっきりしない。どっちつかずである。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "彼の煮え切らない態度に、いらいらした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "波風が立つ",
    "japanese": "平穏な生活や状態が破られる。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "余計な一言で、家庭に波風が立った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "斜めに読む",
    "japanese": "大事なところだけ注意して、さっと読む。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "時間がないので、新聞を斜めに読んだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "涙をのむ",
    "japanese": "悔しさをこらえる。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "あと一歩で敗れ、涙をのんだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "二の句が継げない",
    "japanese": "あきれて次に言う言葉が出ない。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "あまりの言い分に、二の句が継げなかった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "二の舞",
    "japanese": "前の人と同じ失敗をすること。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "先輩の二の舞にならないよう気をつける。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "熱に浮かされる",
    "japanese": "のぼせあがって夢中になる。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "熱に浮かされたように、ゲームに没頭した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "音を上げる",
    "japanese": "我慢しきれず降参する。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "きびしい練習に、とうとう音を上げた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "荷が重い",
    "japanese": "責任や負担が大きすぎる。",
    "yomi": "",
    "category": "その他な行",
    "superCategory": "その他の慣用句",
    "example": "新人の私には、この大役は荷が重い。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "はかりに掛ける",
    "japanese": "どちらが得か、はかりに掛けて比べる。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "損得をはかりに掛けて考える。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "薄氷を踏む",
    "japanese": "びくびくしながら危険を冒す。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "薄氷を踏む思いで、危機を乗り越えた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "話がはずむ",
    "japanese": "いきいきと会話が進む。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "共通の趣味で話がはずんだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "話がつく",
    "japanese": "相談や交渉ごとがまとまる。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "双方が譲り合い、無事に話がついた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "幅を利かせる",
    "japanese": "思いのままに勢力をふるう。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "その地域では、彼が幅を利かせている。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "腫れ物にさわるよう",
    "japanese": "気をつかって接する様子。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "機嫌が悪く、腫れ物にさわるように接した。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "一筋縄ではいかない",
    "japanese": "ふつうのやり方では思うようにならない。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "あの相手は、一筋縄ではいかない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "火に油を注ぐ",
    "japanese": "さらに勢いづける。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "彼の一言が、火に油を注ぐ結果になった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "火花を散らす",
    "japanese": "戦いなどを激しく争う。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "両者は優勝をかけて火花を散らした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "火蓋を切る",
    "japanese": "戦いなどを開始する。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "いよいよ選挙戦の火蓋が切られた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "拍子抜け",
    "japanese": "予想外の事態に張り合いがなくなること。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "案外簡単にできたので、拍子抜けした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "膝を交える",
    "japanese": "うちとけて話し合う。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "膝を交えて、じっくり語り合った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "額に汗する",
    "japanese": "一生懸命に働く。",
    "yomi": "",
    "category": "その他は行",
    "superCategory": "その他の慣用句",
    "example": "額に汗して働く姿は美しい。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "枚挙にいとまがない",
    "japanese": "例を挙げきれないほど多い。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "彼の功績は枚挙にいとまがない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "待てど暮らせど",
    "japanese": "いくら待ち続けても。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "待てど暮らせど、返事が返ってこない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "水に流す",
    "japanese": "なかったことにする。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "過ぎたことは水に流そう。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "水の泡",
    "japanese": "努力がむだになること。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "油断して、これまでの苦労が水の泡になった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "水をさす",
    "japanese": "じゃまをする。仲のよい間柄を不和にする。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "せっかくの盛り上がりに水をさすな。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "水を向ける",
    "japanese": "相手の気持ちをある方向へと誘いかける。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "こちらから水を向けると、彼は語り始めた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "身も蓋もない",
    "japanese": "露骨すぎて味もそっけもない。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "そう言ってしまっては身も蓋もない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "名状しがたい",
    "japanese": "言葉で表すことができない。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "名状しがたい不安に襲われた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "ものにする",
    "japanese": "①手に入れる。②技術などを身につける。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "②練習して、手話をものにした。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": false
  },
  {
    "english": "墓穴を掘る",
    "japanese": "自分自身で失敗の原因を作る。",
    "yomi": "",
    "category": "その他ま行",
    "superCategory": "その他の慣用句",
    "example": "余計な言い訳をして、自ら墓穴を掘った。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "矢継ぎ早",
    "japanese": "次々に行うこと。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "記者から矢継ぎ早に質問が飛んだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "山を張る",
    "japanese": "万一の的中を考えにして何かをする。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "試験で山を張ったが、見事に外れた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "槍玉にあげる",
    "japanese": "ある人を攻撃の対象とする。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "彼一人を槍玉にあげるのは不公平だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "弓を引く",
    "japanese": "権力者に反抗する。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "恩ある人に弓を引くことはできない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "らちがあかない",
    "japanese": "はかどらない。物事のきまりがつかない。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "言い争っていても、らちがあかない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "痩せても枯れても",
    "japanese": "どんなに落ちぶれても。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "痩せても枯れても、私は職人だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "矢も盾もたまらず",
    "japanese": "いちずに思いつめて、自分をおさえきれない様子。",
    "yomi": "",
    "category": "その他や行",
    "superCategory": "その他の慣用句",
    "example": "知らせを聞き、矢も盾もたまらず駆けつけた。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "脇目も振らず",
    "japanese": "一つのことだけに熱中する。",
    "yomi": "",
    "category": "その他わ行",
    "superCategory": "その他の慣用句",
    "example": "脇目も振らず勉強に打ち込んだ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "枠にはめる",
    "japanese": "制限や制約を加える。",
    "yomi": "",
    "category": "その他わ行",
    "superCategory": "その他の慣用句",
    "example": "子どもを枠にはめる教育には反対だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "渡りに船",
    "japanese": "ちょうど都合のよいことに出会う。",
    "yomi": "",
    "category": "その他わ行",
    "superCategory": "その他の慣用句",
    "example": "迷っていたところに誘われ、渡りに船だった。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "割に合わない",
    "japanese": "損になる。",
    "yomi": "",
    "category": "その他わ行",
    "superCategory": "その他の慣用句",
    "example": "苦労のわりに報われず、割に合わない。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  },
  {
    "english": "輪をかける",
    "japanese": "さらに程度を大きくする。",
    "yomi": "",
    "category": "その他わ行",
    "superCategory": "その他の慣用句",
    "example": "兄も乱暴だが、弟は輪をかけて乱暴だ。",
    "exampleJapanese": "",
    "bigCategory": "その他の慣用句",
    "exampleAI": true
  }
];
